/* 
 * Vmoso API
 *
 * Vmoso API
 *
 * OpenAPI spec version: 2.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace VmosoApiClient.Model
{
    /// <summary>
    /// CreateWidgetInput
    /// </summary>
    [DataContract]
    public partial class CreateWidgetInput :  IEquatable<CreateWidgetInput>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateWidgetInput" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateWidgetInput() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateWidgetInput" /> class.
        /// </summary>
        /// <param name="Widget">Widget (required).</param>
        /// <param name="Destinations">.</param>
        public CreateWidgetInput(WidgetV2Record Widget = null, List<string> Destinations = null)
        {
            // to ensure "Widget" is required (not null)
            if (Widget == null)
            {
                throw new InvalidDataException("Widget is a required property for CreateWidgetInput and cannot be null");
            }
            else
            {
                this.Widget = Widget;
            }
            this.Destinations = Destinations;
        }
        
        /// <summary>
        /// Gets or Sets Widget
        /// </summary>
        [DataMember(Name="widget", EmitDefaultValue=false)]
        public WidgetV2Record Widget { get; set; }
        /// <summary>
        /// 
        /// </summary>
        /// <value></value>
        [DataMember(Name="destinations", EmitDefaultValue=false)]
        public List<string> Destinations { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateWidgetInput {\n");
            sb.Append("  Widget: ").Append(Widget).Append("\n");
            sb.Append("  Destinations: ").Append(Destinations).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as CreateWidgetInput);
        }

        /// <summary>
        /// Returns true if CreateWidgetInput instances are equal
        /// </summary>
        /// <param name="other">Instance of CreateWidgetInput to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateWidgetInput other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Widget == other.Widget ||
                    this.Widget != null &&
                    this.Widget.Equals(other.Widget)
                ) && 
                (
                    this.Destinations == other.Destinations ||
                    this.Destinations != null &&
                    this.Destinations.SequenceEqual(other.Destinations)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Widget != null)
                    hash = hash * 59 + this.Widget.GetHashCode();
                if (this.Destinations != null)
                    hash = hash * 59 + this.Destinations.GetHashCode();
                return hash;
            }
        }
    }

}
