/* 
 * Vmoso API
 *
 * Vmoso API
 *
 * OpenAPI spec version: 2.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace VmosoApiClient.Model
{
    /// <summary>
    /// SaveInput
    /// </summary>
    [DataContract]
    public partial class SaveInput :  IEquatable<SaveInput>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SaveInput" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SaveInput() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SaveInput" /> class.
        /// </summary>
        /// <param name="DominantActivity"> (required).</param>
        /// <param name="Filename"> (required).</param>
        public SaveInput(bool? DominantActivity = null, string Filename = null)
        {
            // to ensure "DominantActivity" is required (not null)
            if (DominantActivity == null)
            {
                throw new InvalidDataException("DominantActivity is a required property for SaveInput and cannot be null");
            }
            else
            {
                this.DominantActivity = DominantActivity;
            }
            // to ensure "Filename" is required (not null)
            if (Filename == null)
            {
                throw new InvalidDataException("Filename is a required property for SaveInput and cannot be null");
            }
            else
            {
                this.Filename = Filename;
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
        /// <value></value>
        [DataMember(Name="dominantActivity", EmitDefaultValue=false)]
        public bool? DominantActivity { get; set; }
        /// <summary>
        /// 
        /// </summary>
        /// <value></value>
        [DataMember(Name="filename", EmitDefaultValue=false)]
        public string Filename { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SaveInput {\n");
            sb.Append("  DominantActivity: ").Append(DominantActivity).Append("\n");
            sb.Append("  Filename: ").Append(Filename).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as SaveInput);
        }

        /// <summary>
        /// Returns true if SaveInput instances are equal
        /// </summary>
        /// <param name="other">Instance of SaveInput to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SaveInput other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.DominantActivity == other.DominantActivity ||
                    this.DominantActivity != null &&
                    this.DominantActivity.Equals(other.DominantActivity)
                ) && 
                (
                    this.Filename == other.Filename ||
                    this.Filename != null &&
                    this.Filename.Equals(other.Filename)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.DominantActivity != null)
                    hash = hash * 59 + this.DominantActivity.GetHashCode();
                if (this.Filename != null)
                    hash = hash * 59 + this.Filename.GetHashCode();
                return hash;
            }
        }
    }

}
