/* 
 * Vmoso API
 *
 * Vmoso API
 *
 * OpenAPI spec version: 2.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace VmosoApiClient.Model
{
    /// <summary>
    /// SetPublicInput
    /// </summary>
    [DataContract]
    public partial class SetPublicInput :  IEquatable<SetPublicInput>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SetPublicInput" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SetPublicInput() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SetPublicInput" /> class.
        /// </summary>
        /// <param name="_Public"> (required).</param>
        public SetPublicInput(bool? _Public = null)
        {
            // to ensure "_Public" is required (not null)
            if (_Public == null)
            {
                throw new InvalidDataException("_Public is a required property for SetPublicInput and cannot be null");
            }
            else
            {
                this._Public = _Public;
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
        /// <value></value>
        [DataMember(Name="public", EmitDefaultValue=false)]
        public bool? _Public { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SetPublicInput {\n");
            sb.Append("  _Public: ").Append(_Public).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as SetPublicInput);
        }

        /// <summary>
        /// Returns true if SetPublicInput instances are equal
        /// </summary>
        /// <param name="other">Instance of SetPublicInput to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SetPublicInput other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this._Public == other._Public ||
                    this._Public != null &&
                    this._Public.Equals(other._Public)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this._Public != null)
                    hash = hash * 59 + this._Public.GetHashCode();
                return hash;
            }
        }
    }

}
