/* 
 * Vmoso API
 *
 * Vmoso API
 *
 * OpenAPI spec version: 2.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace VmosoApiClient.Model
{
    /// <summary>
    /// StreamCountRecord
    /// </summary>
    [DataContract]
    public partial class StreamCountRecord :  IEquatable<StreamCountRecord>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StreamCountRecord" /> class.
        /// </summary>
        /// <param name="Count">Count for set of differentials.</param>
        /// <param name="Differentials">Set of differentials that the count is for.</param>
        public StreamCountRecord(int? Count = null, List<OptionDifferentialRecord> Differentials = null)
        {
            this.Count = Count;
            this.Differentials = Differentials;
        }
        
        /// <summary>
        /// Count for set of differentials
        /// </summary>
        /// <value>Count for set of differentials</value>
        [DataMember(Name="count", EmitDefaultValue=false)]
        public int? Count { get; set; }
        /// <summary>
        /// Set of differentials that the count is for
        /// </summary>
        /// <value>Set of differentials that the count is for</value>
        [DataMember(Name="differentials", EmitDefaultValue=false)]
        public List<OptionDifferentialRecord> Differentials { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class StreamCountRecord {\n");
            sb.Append("  Count: ").Append(Count).Append("\n");
            sb.Append("  Differentials: ").Append(Differentials).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as StreamCountRecord);
        }

        /// <summary>
        /// Returns true if StreamCountRecord instances are equal
        /// </summary>
        /// <param name="other">Instance of StreamCountRecord to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(StreamCountRecord other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Count == other.Count ||
                    this.Count != null &&
                    this.Count.Equals(other.Count)
                ) && 
                (
                    this.Differentials == other.Differentials ||
                    this.Differentials != null &&
                    this.Differentials.SequenceEqual(other.Differentials)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Count != null)
                    hash = hash * 59 + this.Count.GetHashCode();
                if (this.Differentials != null)
                    hash = hash * 59 + this.Differentials.GetHashCode();
                return hash;
            }
        }
    }

}
