/* 
 * Vmoso API
 *
 * Vmoso API
 *
 * OpenAPI spec version: 2.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace VmosoApiClient.Model
{
    /// <summary>
    /// UpdateRuleInput
    /// </summary>
    [DataContract]
    public partial class UpdateRuleInput :  IEquatable<UpdateRuleInput>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateRuleInput" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UpdateRuleInput() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateRuleInput" /> class.
        /// </summary>
        /// <param name="Rule">Rule (required).</param>
        public UpdateRuleInput(RuleRecord Rule = null)
        {
            // to ensure "Rule" is required (not null)
            if (Rule == null)
            {
                throw new InvalidDataException("Rule is a required property for UpdateRuleInput and cannot be null");
            }
            else
            {
                this.Rule = Rule;
            }
        }
        
        /// <summary>
        /// Gets or Sets Rule
        /// </summary>
        [DataMember(Name="rule", EmitDefaultValue=false)]
        public RuleRecord Rule { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UpdateRuleInput {\n");
            sb.Append("  Rule: ").Append(Rule).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as UpdateRuleInput);
        }

        /// <summary>
        /// Returns true if UpdateRuleInput instances are equal
        /// </summary>
        /// <param name="other">Instance of UpdateRuleInput to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UpdateRuleInput other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Rule == other.Rule ||
                    this.Rule != null &&
                    this.Rule.Equals(other.Rule)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Rule != null)
                    hash = hash * 59 + this.Rule.GetHashCode();
                return hash;
            }
        }
    }

}
