/* 
 * Vmoso API
 *
 * Vmoso API
 *
 * OpenAPI spec version: 2.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace VmosoApiClient.Model
{
    /// <summary>
    /// UpdateReferencesInput
    /// </summary>
    [DataContract]
    public partial class UpdateReferencesInput :  IEquatable<UpdateReferencesInput>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateReferencesInput" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UpdateReferencesInput() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateReferencesInput" /> class.
        /// </summary>
        /// <param name="AddedObjectKeys">.</param>
        /// <param name="ReferenceType"> (required).</param>
        public UpdateReferencesInput(List<string> AddedObjectKeys = null, string ReferenceType = null)
        {
            // to ensure "ReferenceType" is required (not null)
            if (ReferenceType == null)
            {
                throw new InvalidDataException("ReferenceType is a required property for UpdateReferencesInput and cannot be null");
            }
            else
            {
                this.ReferenceType = ReferenceType;
            }
            this.AddedObjectKeys = AddedObjectKeys;
        }
        
        /// <summary>
        /// 
        /// </summary>
        /// <value></value>
        [DataMember(Name="addedObjectKeys", EmitDefaultValue=false)]
        public List<string> AddedObjectKeys { get; set; }
        /// <summary>
        /// 
        /// </summary>
        /// <value></value>
        [DataMember(Name="referenceType", EmitDefaultValue=false)]
        public string ReferenceType { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UpdateReferencesInput {\n");
            sb.Append("  AddedObjectKeys: ").Append(AddedObjectKeys).Append("\n");
            sb.Append("  ReferenceType: ").Append(ReferenceType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as UpdateReferencesInput);
        }

        /// <summary>
        /// Returns true if UpdateReferencesInput instances are equal
        /// </summary>
        /// <param name="other">Instance of UpdateReferencesInput to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UpdateReferencesInput other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.AddedObjectKeys == other.AddedObjectKeys ||
                    this.AddedObjectKeys != null &&
                    this.AddedObjectKeys.SequenceEqual(other.AddedObjectKeys)
                ) && 
                (
                    this.ReferenceType == other.ReferenceType ||
                    this.ReferenceType != null &&
                    this.ReferenceType.Equals(other.ReferenceType)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.AddedObjectKeys != null)
                    hash = hash * 59 + this.AddedObjectKeys.GetHashCode();
                if (this.ReferenceType != null)
                    hash = hash * 59 + this.ReferenceType.GetHashCode();
                return hash;
            }
        }
    }

}
