/* 
 * Vmoso API
 *
 * Vmoso API
 *
 * OpenAPI spec version: 2.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace VmosoApiClient.Model
{
    /// <summary>
    /// WorkflowPayloadMetaRecord
    /// </summary>
    [DataContract]
    public partial class WorkflowPayloadMetaRecord :  IEquatable<WorkflowPayloadMetaRecord>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkflowPayloadMetaRecord" /> class.
        /// </summary>
        /// <param name="Modes">Access modes corresponding to {@link roles}..</param>
        /// <param name="DisplayName">Payload display name..</param>
        /// <param name="Roles">Roles with access..</param>
        /// <param name="Name">Name of payload..</param>
        /// <param name="Perms">Permissions corresponding to {@link roles}..</param>
        public WorkflowPayloadMetaRecord(List<string> Modes = null, string DisplayName = null, List<string> Roles = null, string Name = null, List<string> Perms = null)
        {
            this.Modes = Modes;
            this.DisplayName = DisplayName;
            this.Roles = Roles;
            this.Name = Name;
            this.Perms = Perms;
        }
        
        /// <summary>
        /// Access modes corresponding to {@link roles}.
        /// </summary>
        /// <value>Access modes corresponding to {@link roles}.</value>
        [DataMember(Name="modes", EmitDefaultValue=false)]
        public List<string> Modes { get; set; }
        /// <summary>
        /// Payload display name.
        /// </summary>
        /// <value>Payload display name.</value>
        [DataMember(Name="displayName", EmitDefaultValue=false)]
        public string DisplayName { get; set; }
        /// <summary>
        /// Roles with access.
        /// </summary>
        /// <value>Roles with access.</value>
        [DataMember(Name="roles", EmitDefaultValue=false)]
        public List<string> Roles { get; set; }
        /// <summary>
        /// Name of payload.
        /// </summary>
        /// <value>Name of payload.</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }
        /// <summary>
        /// Permissions corresponding to {@link roles}.
        /// </summary>
        /// <value>Permissions corresponding to {@link roles}.</value>
        [DataMember(Name="perms", EmitDefaultValue=false)]
        public List<string> Perms { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class WorkflowPayloadMetaRecord {\n");
            sb.Append("  Modes: ").Append(Modes).Append("\n");
            sb.Append("  DisplayName: ").Append(DisplayName).Append("\n");
            sb.Append("  Roles: ").Append(Roles).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Perms: ").Append(Perms).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as WorkflowPayloadMetaRecord);
        }

        /// <summary>
        /// Returns true if WorkflowPayloadMetaRecord instances are equal
        /// </summary>
        /// <param name="other">Instance of WorkflowPayloadMetaRecord to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(WorkflowPayloadMetaRecord other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Modes == other.Modes ||
                    this.Modes != null &&
                    this.Modes.SequenceEqual(other.Modes)
                ) && 
                (
                    this.DisplayName == other.DisplayName ||
                    this.DisplayName != null &&
                    this.DisplayName.Equals(other.DisplayName)
                ) && 
                (
                    this.Roles == other.Roles ||
                    this.Roles != null &&
                    this.Roles.SequenceEqual(other.Roles)
                ) && 
                (
                    this.Name == other.Name ||
                    this.Name != null &&
                    this.Name.Equals(other.Name)
                ) && 
                (
                    this.Perms == other.Perms ||
                    this.Perms != null &&
                    this.Perms.SequenceEqual(other.Perms)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Modes != null)
                    hash = hash * 59 + this.Modes.GetHashCode();
                if (this.DisplayName != null)
                    hash = hash * 59 + this.DisplayName.GetHashCode();
                if (this.Roles != null)
                    hash = hash * 59 + this.Roles.GetHashCode();
                if (this.Name != null)
                    hash = hash * 59 + this.Name.GetHashCode();
                if (this.Perms != null)
                    hash = hash * 59 + this.Perms.GetHashCode();
                return hash;
            }
        }
    }

}
